Add: GUI-Template
PM-Dungeon/dungeon-starter pull request #114
Opened 2022-05-20 19:19 UTC by TGrothe

Template für einen MenuScreen.

Status: draft

2022-05-22 09:25 UTC, TGrothe commented
Ich hab ein einfaches Menü-System (DropDownMenu bzw. Up) hinzugefügt. Das muss aber noch refactored werden.

2022-05-22 11:48 UTC, TGrothe commented
Bin mit dem Refactoring erstmal durch...

@jedi101 Könntest du die TextButton vielleicht schöner gestalten? Vielleicht mit einem eigenen Skin? Oder hast du noch Ideen dazu?

2022-05-23 06:06 UTC, jedi101 commented
@TGrothe - Sorry, bin da noch nicht zu gekommen. Habe mir glaube ich eine Erkältung eingefangen. Ich versuche da gleich mal  ein Skin für zu erstellen.

2022-05-23 07:02 UTC, TGrothe commented
> @TGrothe - Sorry, bin da noch nicht zu gekommen. Habe mir glaube ich eine Erkältung eingefangen. Ich versuche da gleich mal ein Skin für zu erstellen.

Moin und gute Besserung. Das muss aber auch nicht unbedingt eine eigene Skin sein. Mir fallen im Moment nur keine Verbesserungsvorschläge für das Menüsystem ein.

2022-05-23 19:51 UTC, AMatutat commented
Mal Frage für mich: Das dient doch "nur" als proof of concept für die mögliche Vorlesung, richtig?
Wir mergen das doch nicht

2022-05-23 19:54 UTC, TGrothe commented
> Mal Frage für mich: Das dient doch "nur" als proof of concept für die mögliche Vorlesung, richtig? Wir mergen das doch nicht

Wir könnten das mergen, aber dann muss ich noch ein paar kleinere Anpassungen vornehmen.

2022-05-23 19:57 UTC, TGrothe commented
...ich dachte, der Review Request käme sonst nicht bei euch an ... :/

2022-05-23 20:04 UTC, AMatutat commented
> ...ich dachte, der Review Request käme sonst nicht bei euch an ... :/

puh ähh, keine Ahnung.... Gute frage.... Ich glaube die kommen auch so durch....

2022-05-23 20:06 UTC, TGrothe commented
> > ...ich dachte, der Review Request käme sonst nicht bei euch an ... :/
> 
> puh ähh, keine Ahnung.... Gute frage.... Ich glaube die kommen auch so durch....

das "Blaue Glocke Phänomen" 🤣

2022-05-24 08:38 UTC, AMatutat commented
> hmmm, das könnte man im prinzip auch mergen, oder? wenn das alles mal fertig ist, könnten die studis dann eigene menüs damit bauen...

Dann muss das aber noch entsprechend aufgeräumt werden (die ganzen Demo Sachen raus). Aber macht das mal erst nachdem die Vorlesung steht.

2022-05-24 09:56 UTC, TGrothe commented
> hmmm, das könnte man im prinzip auch mergen, oder? wenn das alles mal fertig ist, könnten die studis dann eigene menüs damit bauen...

Das finde ich eine gute Idee. =) Ich kann das, nachdem die Vorlesung steht, vorbereiten.

2022-06-01 17:24 UTC, TGrothe commented
Dieser könnte jetzt gemerged werden. =) @cagix

2022-06-01 17:58 UTC, jedi101 commented
>Dieser könnte jetzt gemerged werden. =) @cagix

@TGrothe - Hm wenn wir den so in den Master übernehmen würden, dann würde man ja den Studis die bereits ein Menü bei sich implementiert haben ein Menü über ihr eigenes legen. Wäre es da nicht besser, wir bereiten das was Du gemacht hast um die Menüstruktur zu erstellen soweit für Carstens Vorlesung auf? Ein direkten "Merge" in den Master würde bestimmt gehen, aber für zukünftige Studis müsste dann glaube ich der Quickstartguide dahingehend ergänzt werden und für derzeitige Studis wäre eine kurze Erklärung dazu in einer VL schon hilfreich. Oder übersehe ich da gerade etwas?

2022-06-02 07:09 UTC, cagix commented
@TGrothe Welcher PR ist jetzt eigentlich welcher? Also welcher _soll_ gemergt werden und welcher soll nur die Sachen für die Vorlesung "offen" halten?

2022-06-02 07:10 UTC, cagix commented
> > Dieser könnte jetzt gemerged werden. =) @cagix
> 
> @TGrothe - Hm wenn wir den so in den Master übernehmen würden, dann würde man ja den Studis die bereits ein Menü bei sich implementiert haben ein Menü über ihr eigenes legen. Wäre es da nicht besser, wir bereiten das was Du gemacht hast um die Menüstruktur zu erstellen soweit für Carstens Vorlesung auf? Ein direkten "Merge" in den Master würde bestimmt gehen, aber für zukünftige Studis müsste dann glaube ich der Quickstartguide dahingehend ergänzt werden und für derzeitige Studis wäre eine kurze Erklärung dazu in einer VL schon hilfreich. Oder übersehe ich da gerade etwas?

Ohne in den Code geschaut zu haben: Kann man die Funktionalität nicht als "Add-On" bereitstellen? D.h. wer die nicht aufruft, merkt nix davon? Dadurch stören wir diejenigen nicht, die selbst was implementiert haben in dieser Richtung ... 

Und ja, der Quick-Start sollte ergänzt werden.

2022-06-02 09:22 UTC, TGrothe commented on code/desktop/src/desktop/MyGame.java
> +        addDemoMenuEntries();
@cagix Es ist ja als AddOn gedacht. Wenn diese beiden Methoden nicht aufgerufen werden, dann stören wir die anderen auch nicht.

2022-06-02 09:30 UTC, TGrothe commented
> @TGrothe Welcher PR ist jetzt eigentlich welcher? Also welcher _soll_ gemergt werden und welcher soll nur die Sachen für die Vorlesung "offen" halten?

Dieser #114 soll gemerged werden, und #117 beinhaltet nur Dinge für die VL.

2022-06-02 09:32 UTC, TGrothe commented
> > > Dieser könnte jetzt gemerged werden. =) @cagix
> > 
> > 
> > @TGrothe - Hm wenn wir den so in den Master übernehmen würden, dann würde man ja den Studis die bereits ein Menü bei sich implementiert haben ein Menü über ihr eigenes legen. Wäre es da nicht besser, wir bereiten das was Du gemacht hast um die Menüstruktur zu erstellen soweit für Carstens Vorlesung auf? Ein direkten "Merge" in den Master würde bestimmt gehen, aber für zukünftige Studis müsste dann glaube ich der Quickstartguide dahingehend ergänzt werden und für derzeitige Studis wäre eine kurze Erklärung dazu in einer VL schon hilfreich. Oder übersehe ich da gerade etwas?
> 
> Ohne in den Code geschaut zu haben: Kann man die Funktionalität nicht als "Add-On" bereitstellen? D.h. wer die nicht aufruft, merkt nix davon? Dadurch stören wir diejenigen nicht, die selbst was implementiert haben in dieser Richtung ...
> 
> Und ja, der Quick-Start sollte ergänzt werden.

Dann muss ich nur Zeile 28 und 29 auskommentieren. Den Quickstart kann ich ergänzen, oder möchte @jedi101 das machen?

2022-06-02 09:38 UTC, TGrothe commented
@jedi101 Du würdest mir dabei viel Arbeit abnehmen. :) Ich kann nicht so gut formulieren. Eigentlich brauchen wir im Quickstart ganz unten nur einen zusätzlichen Abschnitt: "Startmenü hinzufügen" oder Ähnliches und ein paar Beispielmethodenaufrufe...

2022-06-02 09:47 UTC, cagix commented
> > @TGrothe Welcher PR ist jetzt eigentlich welcher? Also welcher _soll_ gemergt werden und welcher soll nur die Sachen für die Vorlesung "offen" halten?
> 
> 
> 
> Dieser #114 soll gemerged werden, und #117 beinhaltet nur Dinge für die VL.

kannst bitte die titel entsprechend anpassen? und auch einen satz in fie summary dazu schreiben?

2022-06-02 09:49 UTC, jedi101 commented
> Dann muss ich nur die Zeile 28 und 30 auskommentieren. Den Quickstart kann ich ergänzen, oder möchte @jedi101 das machen?

Ja, das mache ich dann @TGrothe.

2022-06-02 12:09 UTC, TGrothe commented
> > Dieser #114 soll gemerged werden, und #117 beinhaltet nur Dinge für die VL.
> 
> kannst bitte die titel entsprechend anpassen? und auch einen satz in die summary dazu schreiben?

Danke, das hab ich gemacht, sollte jetzt ok sein.

2022-06-03 08:07 UTC, cagix commented on code/desktop/src/desktop/MyGame.java
> +                        System.out.println("An item clicked.");
`System.out.println` im Produktivcode? Bitte auf Logger umstellen.

2022-06-03 08:45 UTC, TGrothe commented on code/desktop/src/desktop/MyGame.java
> +                        System.out.println("An item clicked.");
Oki, siehe 5e0667e

2022-06-03 09:34 UTC, jedi101 commented on code/desktop/src/desktop/MyGame.java
> +        // addDemoMenuEntries();
Sollten wir das im Code so drin stehen lassen oder besser im Quickstartguide dann diese Zeilen als Vorgabe geben wenn sie ein Startmenü angezeigt bekommen sollen?

2022-06-03 09:53 UTC, cagix commented on code/desktop/src/desktop/MyGame.java
> +        // addDemoMenuEntries();
Keine auskommentierten Codeteile. Quickstart klingt nach einer guten Alternative - das muss ja eh erklärt werden, wie man das aufbaut und damit arbeitet. Da kann auch das Schnipselchen untergebracht werden. ... Und `addDemoMenuEntries()` ist ja eh eine Art Easter-Egg, oder? Sowas würde man in der Bibliothek ja eigentlich nicht einbauen :)

2022-06-03 09:59 UTC, cagix commented on code/desktop/src/desktop/MyGame.java
> +        // addDemoMenuEntries();
Das bringt mich wieder zum Nachdenken. Wir haben unser Core als Framework - damit könnte man direkt loslegen und den Kram schrittweise aufbauen.

Das Desktop soll für die Studis einen leichteren Einstieg ermöglichen, indem ein paar Sachen schon vorgegeben werden. 

Andererseits haben wir den Quickstart-Guide, den die Studis Schritt für Schritt nachbauen (sollen/können). Damit ist eigentlich der Desktop obsolet, weil man den Quickstart eigentlich auch direkt auf dem Core ausführen könnte, oder? 

Dazu kommt noch die Sache mit den ganzen Konfig-Dateien, die wir in beiden Repos pflegen (müssen).

Wäre es nicht sinnvoller, wenn wir das Desktop-Repo in eine Art Demo umbauen, wo wir bestimmte Basissachen zeigen und die Studis hier bestimmte Techniken studieren lassen? Also nicht so sehr als Startpunkt für die eigene Entwicklung, sondern eher eine Art Studienobjekt? Dann könnte man auch (wie die Studis dann) auf Core aufsetzen (als Klon) und würde sich zusätzlich ersparen, welches der beiden Repos denn nun die Source-of-Truth ist (Wie oft haben wir den Quickstart hin und her geschoben? Wie oft kopieren wir Dinge von dem einen Repo ins andere?).

@TGrothe @AMatutat @jedi101 Meinungen? Lohnt sich ein neues Ticket, um darüber nachzudenken?

2022-06-03 10:23 UTC, TGrothe commented on code/desktop/src/desktop/MyGame.java
> +        // addDemoMenuEntries();
> @TGrothe @AMatutat @jedi101 Meinungen? Lohnt sich ein neues Ticket, um darüber nachzudenken?

Ja, ich finde die Überlegung aus den genannten Gründen sinnvoll ...

Ein "Nachteil wäre natürlich aus meiner Sicht, dass dann direkte Änderungen am Core möglich wären...

2022-06-03 10:33 UTC, TGrothe commented on code/desktop/src/desktop/MyGame.java
> +        // addDemoMenuEntries();
> Sollten wir das im Code so drin stehen lassen? Oder ist es an dieser Stelle vielleicht besser auf die Möglichkeit eines Startmenüs im Quickstartguide einzugehen?

Ich hätte jetzt gesagt, beides wäre gut, aber im Quickstart sollte das auf jeden fall stehen...

So lange nehme ich das erst mal noch nicht raus...

2022-06-03 10:33 UTC, jedi101 commented on code/desktop/src/desktop/MyGame.java
> +        // addDemoMenuEntries();
> Ein "Nachteil wäre natürlich aus meiner Sicht, dass dann direkte Änderungen am Core möglich wären...

Hm, das stimmt. Wäre das denn eigentlich schlimm? Die Studis die fit genug sind um den Core umzuschreiben um ihre Art des Dungeon zu implementieren können das meiner Meinung auch gerne machen und für alle anderen bietet der Quickstartguide dann eine entsprechende Vorlage um sich mit dem Framework vertraut zu machen. Aber ich glaube @AMatutat hatte da, als das Thema das letzte mal aufkam, ein Paar Punkte aufgeführt die es dabei zu bedenken gab?

2022-06-03 10:35 UTC, TGrothe commented on code/desktop/src/desktop/MyGame.java
> +        // addDemoMenuEntries();
@jedi101 Siehe neues Ticket #119 😉

2022-06-03 11:36 UTC, AMatutat requested changes
Irgendwie machen mir die ungenutzten aber überschriebenen Methoden Bauchweh.
Auf dem Papier klingt das nach einer unpassend gewählten Vererbungs-Struktur, 

Außerdem fehlt so ziemlich überall die Javadoc.

2022-06-03 11:36 UTC, AMatutat commented on code/desktop/src/menu/MenuScreen.java
> +    public void show() {}
Waren werden Methode überschrieben, die dann nix machen?

2022-06-03 11:36 UTC, AMatutat commented on code/desktop/src/menu/MenuScreen.java
> +    public Point getPosition() {
`return null;` ?

Das Ding muss doch eine Position haben

2022-06-03 11:36 UTC, AMatutat commented on code/desktop/src/menu/MenuScreen.java
> +    public String getTexturePath() {
same

2022-06-03 11:41 UTC, jedi101 commented on code/desktop/src/menu/MenuScreen.java
> +    public void show() {}
ich glaube das ist ein Artefakt, das Entsteht, wenn man das Screen interface implementiert.

2022-06-03 11:47 UTC, jedi101 commented on code/desktop/src/menu/MenuScreen.java
> +    public Point getPosition() {
Die Position der hier erstellten "Actor" ist relativ gesetzt, deshalb hat es keine eigentliche "Position" in X und Y Koordinaten sondern vielmehr so etwas wie "bottom, center". Ich glaube deswegen gibt hier `getPosition()` nicht die Position zurück.

2022-06-03 11:50 UTC, jedi101 commented on code/desktop/src/menu/MenuScreen.java
> +    public String getTexturePath() {
Das hier implementierte Menü hat noch keine Textur. Eine Textur würde es erst bei der Verwendung eines `TexturAtlas` bzw. einem dazugehörigen Skin geben, die könnte man an dieser Stelle zurück geben aber in wie weit das sinnig ist kann ich nicht sagen.

2022-06-03 12:24 UTC, TGrothe commented on code/desktop/src/menu/MenuScreen.java
> +    public void show() {}
Danke für die Erklärung. Den `ScreenAdapter` können wir nicht nutzen, weil das Ding ein Hud-Element ist.

2022-06-03 12:26 UTC, TGrothe commented
> Irgendwie machen mir die ungenutzten aber überschriebenen Methoden Bauchweh.
> Auf dem Papier klingt das nach einer unpassend gewählten Vererbungs-Struktur,

Das ist aber schon eine minimale Anpassung, um das Dinge ohne eine Anpassung des Cores zum Laufen zu bekommen (das war die Vorgabe), und der Core sollte hierbei nicht geändert werden.

2022-07-12 12:34 UTC, closed without merging