fix code in quickstart
PM-Dungeon/dungeon-starter pull request #83
Opened 2022-04-09 16:27 UTC by AMatutat

fixes #70 , fixes #69

2022-04-09 17:18 UTC, cagix requested changes
noch zwei vorschläge

und in z.346/348 muss noch ein „java“ an die startenden backticks…

sonst hab ich im markdown jetzt nix gesehen. hast du dir mal die vorschau angesehen, ob das da auch passt?

2022-04-09 17:18 UTC, cagix commented on documentation/quickstart_en.md
> +*Note: We use randomly generated levels in our example, so you probably won't see the exact same level as in our illustrations.
```suggestion
**Note**: We use randomly generated levels in our example, so you probably won't see the exact same level as in our illustrations.
```

2022-04-09 17:18 UTC, cagix commented on documentation/quickstart_de.md
> +*Anmerkung: Wir verwenden in unserem Beispiel zufällig generierte Level, daher werden Sie vermutlich nicht das exakt gleiche Level sehen wie auf unseren Abbildungen.*
```suggestion
**Anmerkung**: Wir verwenden in unserem Beispiel zufällig generierte Level, daher werden Sie vermutlich nicht das exakt gleiche Level sehen wie auf unseren Abbildungen.
```

2022-04-10 15:25 UTC, AMatutat commented
@cagix 
Ich habe die deutsche Variante jetzt aufgearbeitet. 
Erstmal hab ich den spaß an die neue Version angepasst. Außerdem habe ich für die meisten Code-Snippets die vollständige Klasse kopiert. Jetzt kann man zwar besser Copy-Pasten, hat aber auch eine bessere Vorstellung wie der spaß aussehen soll und kann vergleichen. Imports werden nun auch angegeben. 
UML ist geupdated. Formatierung sollte gefixed sein.

2022-04-10 17:23 UTC, cagix requested changes
Ein paar Kleinigkeiten noch. Diese Version gefällt mir deutlich besser als vorher, dennoch würde ich #72 hierdurch noch nicht als gelöst betrachten. Ich habe das Gefühl, dass das nochmal ein paar strukturelle Änderungen braucht (später => "later").

Ich habe den Code jetzt nicht mehr testen können, das würde ich ggf. morgen nachholen (wenn das sinnvoll ist?). Der Code ist aber auch nicht von Dir getestet, oder? Da war mind. ein Syntaxfehler dabei ...

Der Satz "Bevor wir nun unseren Helden implementieren sollten wir verstehen, wie genau die Vorgaben aufgebaut sind. Öffnen Sie dafür das desktop/code-Verzeichnis als Gradle-Projekt in Ihrer bevorzugten IDE." sollte eine eigene Überschrift bekommen, damit das mit dem Öffnen des Ordners deutlich von der Implementierung des Helden abgehoben wird.

Im neuen Code wird `basiselements.Entity` extended, aber im UML gibt es nur `IEntity`. Analog für `HUDElement` im Code und `IHUDElement` im UML.

Vor der Überschrift "Der bewegte (animierte) Held" ist noch ein <hr> oder sowas? `***` scheint den selben Effekt zu haben, bitte entfernen.

2022-04-10 17:23 UTC, cagix commented on documentation/quickstart_de.md
> +    private String texturePath;
@AMatutat @jedi101 

Frage: Jede Entität oder HUDElement hat eine `position` und eine `texture` (bzw. `texturePath`)? Sollte das nicht als protected Feld in der abstrakten Klasse angelegt werden und hier einfach nur genutzt werden? 

Genauso könnten die Methoden dazu bereits in der abstrakten Klasse implementiert werden.

2022-04-10 18:59 UTC, AMatutat commented on documentation/quickstart_de.md
> +        if (Gdx.input.isKeyPressed(Input.Keys.W)) newPosition.y += movementSpeed;
scheinbar nicht

2022-04-10 19:26 UTC, AMatutat commented on documentation/quickstart_de.md
> +    private String texturePath;
Die Methoden sind `abstract` in der Oberklasse definiert, damit vermiede ich `return null`. 
Die Attribute können erst in der konkreten Implementierung initialisiert werden, daher hätten sie in der abstrakten Oberklasse den Wert `null`.

2022-04-10 19:29 UTC, AMatutat commented on documentation/quickstart_de.md
> -### Sound
Ich hab keine Ahnung von der Sound Geschichte. Weiß auch nicht, was ich da deaktivieren soll.

2022-04-10 19:31 UTC, AMatutat commented
> Ich habe den Code jetzt nicht mehr testen können, das würde ich ggf. morgen nachholen (wenn das sinnvoll ist?). Der Code ist aber auch nicht von Dir getestet, oder? Da war mind. ein Syntaxfehler dabei ...

Habs extra nebenbei neu aufgebaut. evtl hab ich da ein copy paste fehler gemacht


> Im neuen Code wird basiselements.Entity extended, aber im UML gibt es nur IEntity. Analog für HUDElement im Code und IHUDElement im UML.

Ich hab das UML doch geupdated.... schau ich mir nachher nochmal an

2022-04-10 20:53 UTC, AMatutat commented on documentation/quickstart_de.md
> +    private String texturePath;
Zusätzlich müssten die Studis dann ein bereits existierendes, für sie aber nicht direkt sichtbares Attribut ändern/setzten. Find ich nicht angenehm.

2022-04-10 20:55 UTC, AMatutat commented on documentation/quickstart_de.md
> +        hero = new MyHero(painter, batch);
wüsste nicht warum?

2022-04-10 20:56 UTC, AMatutat commented on documentation/quickstart_de.md
> +        return lebenpunkte==0;
müsste passen. Hat halt eine Einrückung, weil es eine Methode einer Klasse ist.

2022-04-10 21:00 UTC, AMatutat commented on documentation/quickstart_de.md
> +Zuerst erstellen wir einen Konstruktor für unsere Klasse. Das Framework benötigt eine `SpriteBatch` und einen `Painter` um unseren Helden am Ende zeichnen zu können.
```suggestion
Zuerst erstellen wir einen Konstruktor für unsere Klasse. Das Framework benötigt eine `com.badlogic.gdx.graphics.g2d.SpriteBatch` und einen `graphic.Painter` um unseren Helden am Ende zeichnen zu können.
```

2022-04-10 21:01 UTC, AMatutat commented on documentation/quickstart_de.md
> +        if (Gdx.input.isKeyPressed(Input.Keys.W)) newPosition.y += movementSpeed;
```suggestion
        if (Gdx.input.isKeyPressed(Input.Keys.W)) {
            newPosition.y += movementSpeed;
        }
```

2022-04-10 21:02 UTC, AMatutat commented on documentation/quickstart_de.md
> +        if (Gdx.input.isKeyPressed(Input.Keys.S)) newPosition.y -= movementSpeed;
```suggestion
        if (Gdx.input.isKeyPressed(Input.Keys.S)) {
            newPosition.y -= movementSpeed;
        }
```

2022-04-10 21:02 UTC, AMatutat commented on documentation/quickstart_de.md
> +        if (Gdx.input.isKeyPressed(Input.Keys.D)) newPosition.x += movementSpeed;
```suggestion
        if (Gdx.input.isKeyPressed(Input.Keys.D)) {
            newPosition.x += movementSpeed;
        }
```

2022-04-10 21:03 UTC, AMatutat commented on documentation/quickstart_de.md
> +        if (Gdx.input.isKeyPressed(Input.Keys.A)) newPosition.x -= movementSpeed;
```suggestion
        if (Gdx.input.isKeyPressed(Input.Keys.A)) {
            newPosition.x -= movementSpeed;
        }
```

2022-04-10 21:03 UTC, AMatutat commented on documentation/quickstart_de.md
> +        if (currentLevel.getTileAt(newPosition.toCoordinate()).isAccessible())
```suggestion
        if (currentLevel.getTileAt(newPosition.toCoordinate()).isAccessible()) {
```

2022-04-10 21:04 UTC, AMatutat commented on documentation/quickstart_de.md
> +            this.position = newPosition;
```suggestion
            this.position = newPosition;
        }    
```

2022-04-10 21:11 UTC, AMatutat commented
> Der Satz "Bevor wir nun unseren Helden implementieren sollten wir verstehen, wie genau die Vorgaben aufgebaut sind. Öffnen Sie dafür das desktop/code-Verzeichnis als Gradle-Projekt in Ihrer bevorzugten IDE."

Der Abschnitt hat das doch `## Blick in den Code` 

> Ich habe den Code jetzt nicht mehr testen können, das würde ich ggf. morgen nachholen (wenn das sinnvoll ist?).

Ja, bitte. Sicher ist sicher.

2022-04-11 03:35 UTC, cagix commented on documentation/quickstart_de.md
> +    private String texturePath;
Hmmm, da stimme ich Dir zu. Aus Java-Sicht wäre es geschickter, die gemeinsamen Sachen (Attribute, Methoden) schon in der Oberklasse zu haben, auch wenn das auf `null` hinausläuft. Aber dann sehen die Studis evtl. nicht, dass sie hier was machen müssen.

2022-04-11 03:36 UTC, cagix commented on documentation/quickstart_de.md
> +        hero = new MyHero(painter, batch);
ich meine, irgendwo was gelesen zu haben. einen kommentar von @Tobias321 irgendwo?

2022-04-11 03:36 UTC, cagix commented on documentation/quickstart_de.md
> +        return lebenpunkte==0;
ja, einrückung. aber `lebenspunkte==0` sollte doch eher `lebenspunkte == 0` sein, oder?

2022-04-11 03:38 UTC, cagix commented
> > Der Satz "Bevor wir nun unseren Helden implementieren sollten wir verstehen, wie genau die Vorgaben aufgebaut sind. Öffnen Sie dafür das desktop/code-Verzeichnis als Gradle-Projekt in Ihrer bevorzugten IDE."
> 
> Der Abschnitt hat das doch `## Blick in den Code`
> 

ja, aber das ist immer noch unaufällig. mein vorschlag wäre:

```
## Laden des Projekts in der IDE

Bevor wir nun unseren Helden implementieren sollten wir verstehen, wie genau die Vorgaben aufgebaut sind. 

Öffnen Sie dafür das `desktop/code`-Verzeichnis als Gradle-Projekt in Ihrer bevorzugten IDE.


## Blick in den Code

...
```

2022-04-11 03:39 UTC, cagix commented
> > Ich habe den Code jetzt nicht mehr testen können, das würde ich ggf. morgen nachholen (wenn das sinnvoll ist?).
> 
> Ja, bitte. Sicher ist sicher.

aye. wird aber erst gegen 9 oder so. muss die ruhige zeit jetzt nutzen, um videos aufzunehmen.

2022-04-11 05:55 UTC, cagix commented on documentation/quickstart_de.md
> -### Sound
ich glaube, @Tobias321 hat da was im gradle (raus-) konfiguriert, weil es bei mir (intel-mac) immer die warning wg. audio gab? aber ich kann mich auch irren.

2022-04-11 05:59 UTC, cagix reviewed
Der Satz "Um das PM-Dungeon-Framework zu nutzen erstellen Sie sich einen Fork des [desktop-Repository](https://github.com/PM-Dungeon/desktop) und ziehen sich einen lokalen Klon auf Ihr Gerät." ganz am Anfang unter `## Installation` sollte raus. 

Die Studis haben das Repo ja als Unterordner "desktop" in ihrem Semester-Repo. Kein Grund hier für einen weiteren Fork, d.h. der Hinweis ist in diesem Fall überflüssig/schädlich.

Alternativ müsste der Satz eine entsprechende Ergänzung bekommen für Leute, die direkt das Desktop-Repo ansteuern. Aber eigentlich sollte denen klar sein, dass sie das Repo forken/klonen wollen.

2022-04-11 06:14 UTC, Tobias321 commented on documentation/quickstart_de.md
> -### Sound
Hm, wenn man LWJGL (anstatt LWJGL3) verwendet, dann gibt es bei Macs wohl eine warning. Das Deaktivieren der Sounds ist aber eigentlich nicht nötig.

Wir können mit der warning leben oder LWJGL3 verwenden, dann muss der DesktopLauncher aber geändert werden.

2022-04-11 06:42 UTC, cagix reviewed
@AMatutat Sollte dieser Branch nicht gerebased werden? Es fehlen #82 und #85?

2022-04-11 06:46 UTC, cagix reviewed
> Das Framework ist in ein Frontend (desktop) und ein Backend (core) aufgeteilt. Das Frontend setzt die Parameter, erzeugt ein Fenster und startet die Anwendung. Das Backend liefert die Schnittstellen, mit denen Sie arbeiten, und integriert die libGDX.
> 

Bitte noch einen Satz: "Sie benötigen nur das Frontend (desktop) für die Aufgaben, das Backend wird automatisch über Gradle als externe Bibliothek eingebunden."

> Sie selbst schreiben die Logik des Spiels und implementieren die Helden/Monster/Gegenstände.
> 

Hier sollte noch ein Satz kommen, wo (im Dateisystem) diese Dinge hinkommen (sollen).

2022-04-11 06:48 UTC, cagix commented on documentation/quickstart_de.md
>  Das untenstehende UML-Klassendiagramm soll Ihnen einen reduzierten und vereinfachten Überblick über den Aufbau des Frameworks geben. Es bildet daher nicht alle Klassen/Methoden/Attribute ab. Nutzen S
```suggestion
Das untenstehende UML-Klassendiagramm soll Ihnen einen reduzierten und vereinfachten Überblick über den Aufbau des Frameworks geben. Es bildet daher nicht alle Klassen/Methoden/Attribute ab. Nutzen Sie es als Startpunkt und erforschen Sie die Codebase auf eigene Faust.
```

2022-04-11 06:48 UTC, cagix commented on documentation/quickstart_de.md
>  - Zusätzlich existieren noch eine Vielzahl an weiteren Helferklassen mit dem Sie mal mehr oder mal weniger Kontakt haben werden.
```suggestion
- Zusätzlich existieren noch eine Vielzahl an weiteren Helferklassen, mit denen Sie mal mehr oder mal weniger Kontakt haben werden.
```

2022-04-11 06:51 UTC, cagix reviewed
> Die Vorgaben sind bereits lauffähig und können direkt ausgeführt werden. Dafür können Sie die Vorgaben entweder als Projekt in Ihrer IDE laden und die Anwendung über die Run-Funktion starten oder Sie starten die Anwendung über die Kommandozeile.

Bitte ergänzen: "... entweder als Projekt in Ihrer IDE laden (siehe oben unter "Installation") und die Anwendung ..."

2022-04-11 06:57 UTC, cagix commented on documentation/quickstart_de.md
> +import basiselements.Entity;
`basiselements.Entity` kann nicht aufgelöst werden

<img width="915" alt="Screenshot 2022-04-11 at 08 56 37" src="https://user-images.githubusercontent.com/20356276/162681830-f93358db-24fe-46f8-8253-6b9fb3a87c51.png">

2022-04-11 07:00 UTC, cagix commented on documentation/quickstart_de.md
> +import basiselements.Entity;
weiter komme ich derzeit nicht. die klasse ist nicht auffindbar ...

2022-04-11 08:14 UTC, AMatutat commented on documentation/quickstart_de.md
> +import basiselements.Entity;
Mein Fehler. Hatte vergessen die neue Version auch im build.gradle zu laden bzw. die änderung am build.gradle auch zu pushen, sollte jetzt gehen

2022-04-11 08:15 UTC, cagix commented on documentation/quickstart_de.md
> +import basiselements.Entity;
PS: Ich hatte extra lokal auf den neuen Master rebased ...

2022-04-11 08:19 UTC, jedi101 commented on documentation/quickstart_de.md
> +import basiselements.Entity;
okay, hatte den Quickstartguide vor dem Umbau einmal komplett durch implementiert da sind mir solche Probleme nicht aufgefallen, hattest Du denn beim Umbau des Quickstartguides noch größere Änderungen in der Codebasis vorgenommen @AMatutat? Das ist irgendwie an mir vorbei gegangen. Dann werde ich das glaube ich noch einmal mit dem neuen Quickstartguide machen.

2022-04-11 08:23 UTC, AMatutat commented
> @AMatutat Sollte dieser Branch nicht gerebased werden? Es fehlen https://github.com/PM-Dungeon/desktop/pull/82 und https://github.com/PM-Dungeon/desktop/pull/85?

done

2022-04-11 08:25 UTC, cagix commented on documentation/quickstart_de.md
> +import basiselements.Entity;
> okay, hatte den Quickstartguide vor dem Umbau einmal komplett durch implementiert da sind mir solche Probleme nicht aufgefallen, hattest Du denn beim Umbau des Quickstartguides noch größere Änderungen in der Codebasis vorgenommen @AMatutat? Das ist irgendwie an mir vorbei gegangen. Dann werde ich das glaube ich noch einmal mit dem neuen Quickstartguide machen.

@jedi101 Naja, da waren teilweise schlicht Tippfehler im Guide. Bist Du sicher, dass Du das mal rauskopiert und ausprobiert hattest? Aber ja, es ist eine gute Idee, das nochmal parallel zu mir (intel-mac) auf einer Win-Büchse zu machen. Und bitte aus der Sicht eines typischen 2.-Semestlers.

2022-04-11 08:25 UTC, cagix commented on documentation/quickstart_de.md
> +import basiselements.Entity;
> > , hattest Du denn beim Umbau des Quickstartguides noch größere Änderungen in der Codebasis vorgenommen
> 
> ja, ziemlich große sogar..
> 
> > PS: Ich hatte extra lokal auf den neuen Master rebased ... da war afaik 4.0.0 im gradle drin?
> 
> Sicher? Bei mir findet er es ohne Probleme. 

ja, ziemlich sicher. aber ich zieh mir den kram gleich nochmal und machs nochmal :)

2022-04-11 08:38 UTC, jedi101 commented on documentation/quickstart_de.md
> +import basiselements.Entity;
Also rauskopiert hatte ich das nicht ich hatte mir nur den jeweils beschriebenen Schritt durchgelesen und das dann implementiert. Ich schau noch mal drauf.

2022-04-11 08:51 UTC, AMatutat commented on documentation/quickstart_de.md
> +import basiselements.Entity;
> Also rauskopiert hatte ich das nicht ich hatte mir nur den jeweils beschriebenen Schritt durchgelesen und das dann implementiert. Ich schau noch mal drauf.

Guter Student. So hab ich mir das vorgestellt. @cagix nimm dir doch mal ein Beispiel daran,

2022-04-11 09:15 UTC, cagix commented on documentation/quickstart_de.md
> +import basiselements.Entity;
hä? nixkapier 🤣🤷

2022-04-11 10:57 UTC, jedi101 commented on documentation/quickstart_de.md
> +import basiselements.Entity;
Ich kenne mich mit den subtree sachen nicht aus, müsstest du die neue coreversion 4.0.0 dann auch noch einmal in dem studi vorgaben repo `https://github.com/PM-Dungeon/pm-s22-vorgaben` ändern bzw. den subtree aktualisieren oder ist das dann dort auch automatisch auf die aktuelle version 4.0.0 des `core` gesetzt?

2022-04-11 11:08 UTC, AMatutat commented on documentation/quickstart_de.md
> +import basiselements.Entity;
muss aktualisiert werden, Mache ich heute abend/ morgen früh

2022-04-11 13:59 UTC, jedi101 commented on documentation/quickstart_de.md
> +import basiselements.Entity;
Also ich habe jetzt noch einmal den Quickstart_de guide durchgearbeitet und implementiert. Der neue Quickstartguide ist zwar ziemlich viel copy->paste aber bis auf ein Paar Typos habe ich nichts finden können was auf der Codeseite nicht auch so funktionieren würde wie dort angegeben ist.

2022-04-11 14:17 UTC, AMatutat commented on documentation/quickstart_de.md
> +        return lebenpunkte==0;
```suggestion
        return lebenpunkte == 0;
```

2022-04-11 15:01 UTC, AMatutat commented on documentation/quickstart_de.md
> +        return lebenpunkte==0;
fixed...
manchmal ist dieses plugin komisch.

2022-04-11 15:03 UTC, AMatutat commented on documentation/quickstart_de.md
> -### Sound
siehe #87

2022-04-12 07:17 UTC, cagix commented on documentation/quickstart_de.md
> +Um das Projekt in Ihre IDE zu laden, schauen Sie bitte in das [Desktop-Wiki](https://github.com/PM-Dungeon/desktop/wiki/Import-Project).
```suggestion
Für eine Anleitung, wie Sie das Projekt in Ihrer IDE laden können, schauen Sie bitte in das [Desktop-Wiki: "Import Project"](https://github.com/PM-Dungeon/desktop/wiki/Import-Project).
```

2022-04-12 07:19 UTC, cagix commented on documentation/quickstart_de.md
> +Dafür können Sie die Vorgaben entweder als Projekt in Ihrer IDE laden (siehe oben unter "Installation") und die Anwendung über die Run-Funktion starten oder Sie starten die Anwendung über die Kommand
```suggestion
Dafür können Sie die Vorgaben entweder als Projekt in Ihrer IDE laden (siehe ["Import Project"](https://github.com/PM-Dungeon/desktop/wiki/Import-Project).) und die Anwendung über die Run-Funktion starten oder Sie starten die Anwendung über die Kommandozeile.
```

2022-04-12 07:21 UTC, cagix commented on documentation/quickstart_de.md
>  Jetzt, wo Sie sichergestellt haben, dass das Dungeon ausgeführt werden kann, geht es darum, das Spiel mit Ihren Inhalten zu erweitern. Im Folgenden wird ein rudimentärer Held implementiert, um Ihnen
```suggestion
Jetzt, wo Sie sichergestellt haben, dass das Dungeon ausgeführt werden kann, geht es darum, das Spiel mit Ihren Inhalten zu erweitern. Im Folgenden wird schrittweise ein rudimentärer Held implementiert, um Ihnen die verschiedenen Aspekte des Dungeon zu erläutern.
```

2022-04-12 07:31 UTC, cagix commented on documentation/quickstart_de.md
> +Möchten Sie, dass eine Entität nicht mehr weiter vom `EntityController` verwaltet wird, z.B. wenn sie "stirbt", überschreiben Sie dafür die Methode `removeable` der `Entity`-Klasse. Sobald diese Meth
```suggestion
Möchten Sie, dass Ihr Hero oder eine andere Entität nicht mehr weiter vom `EntityController` verwaltet wird, z.B. wenn sie "stirbt", überschreiben Sie dafür in der jeweiligen Klasse die Methode `removeable`, die von der `Entity`-Klasse geerbt wurde. Sobald diese Methode den Wert `true` zurückgibt, wird die Instanz im nächsten Frame aus dem `EntityController` entfernt.
```

2022-04-12 07:41 UTC, cagix commented on documentation/quickstart_de.md
> +        return lebenpunkte == 0;
`lebenpunkte` ist nicht deklariert ... 

Nachdem oben alles Copy&Paste war und in sich vollständig, sollte hier auch einfach wieder die komplette Klasse angegeben werden. Alternativ müsste man darauf hinweisen, dass es hier nur ein Beispiel ist, wie das gehen könnte und kein funktionierender Schnipsel ...

2022-04-12 07:45 UTC, cagix commented on documentation/quickstart_de.md
>  Wenn Sie das Spiel nun starten, sollten Sie ihren (unbeweglichen) Helden im Dungeon sehen können.
Ich habe den Pfad zur Helden-Textur angepasst auf ein existierendes .png. Aber ein Held wird bei mir nicht angezeigt:

<img width="1274" alt="Screenshot 2022-04-12 at 09 43 39" src="https://user-images.githubusercontent.com/20356276/162907980-264dda37-0a21-4d01-a82c-0f305ead5b2a.png">

2022-04-12 07:47 UTC, cagix commented on documentation/quickstart_de.md
> +        animation.add("assets_path_to_texture/texture_1.png");
Die obigen Beispiele waren Copy&Paste. Hier wird damit gebrochen (ohne Hinweis). Bitte entweder hier existierende Pfade einsetzen oder einen Hinweis.

2022-04-12 07:56 UTC, cagix commented on documentation/quickstart_de.md
> +    private Label levelLabel;
```suggestion
    private com.badlogic.gdx.scenes.scene2d.ui.Label levelLabel;
```

2022-04-12 08:01 UTC, cagix requested changes
etwas Kleinkram und ein paar Anmerkungen ...

2022-04-12 08:05 UTC, Tobias321 commented on documentation/quickstart_de.md
>  Wenn Sie das Spiel nun starten, sollten Sie ihren (unbeweglichen) Helden im Dungeon sehen können.
`this.camera.follow(myHero);` ... (der Held ist außerhalb der View)

2022-04-12 08:16 UTC, cagix commented on documentation/quickstart_de.md
>  Wenn Sie das Spiel nun starten, sollten Sie ihren (unbeweglichen) Helden im Dungeon sehen können.
ah, das war nur das loch in die nächste ebene :) ...

hmmm, das mit der Kamera kommt aber erst später, oder?

2022-04-12 08:26 UTC, cagix commented on documentation/quickstart_de.md
>  Wenn Sie das Spiel nun starten, sollten Sie ihren (unbeweglichen) Helden im Dungeon sehen können.
Seltsam. Ich habe jetzt nochmal alles komplett zurückgesetzt und nochmal die Snippets für `MyHero` (Z. 162 ff) und `MyGame` (Z. 202 ff) über diesem Kommentar genommen (plus einen funktionierenden Texturen-Pfad), und jetzt steht der Held neben dem Loch.

2022-04-12 08:42 UTC, Tobias321 commented
![image](https://user-images.githubusercontent.com/85501570/162919340-3dbe25bc-17e3-4393-9f80-17747c63844d.png)

ohje 😄

2022-04-12 08:47 UTC, Tobias321 commented on documentation/quickstart_de.md
>  Wenn Sie das Spiel nun starten, sollten Sie ihren (unbeweglichen) Helden im Dungeon sehen können.
@cagix Du bist mit der "4.0.+" unterwegs, dann muss dem Hero eigentlich ein Level im Konstruktor übergeben werden... D. h., zuerst der LevelLoader und dann die Entities und Camara... Vielleicht liegt es daran.

2022-04-12 09:08 UTC, AMatutat commented on documentation/quickstart_de.md
> +            levelLabel=hudController.drawText("Level "+levelCounter,"PATH/TO/FONT.ttf",Color.RED,30,50,50,30,30);
> Sind hier nur .ttf erlaubt oder auch andere Fonts?

Hier ist die Doku von libGDX leider nicht wirklich aussagekräftig.

2022-04-12 10:42 UTC, cagix commented on documentation/quickstart_de.md
> +Das Framework ist in `core` und `dungeon-starter` aufgeteilt, wobei `core` das Framework und `dungeon-starter` ein Basis-Starter ist.
```suggestion
Das Framework ist in [`core`](https://github.com/PM-Dungeon/core) und [`dungeon-starter`](https://github.com/PM-Dungeon/dungeon-starter) aufgeteilt, wobei `core` das Framework und `dungeon-starter` ein Basis-Starter ist.
```

2022-04-12 10:42 UTC, cagix commented on documentation/quickstart_de.md
> +Sie benötigen nur das Frontend (dungeon-starter) für die Aufgaben, das Backend wird automatisch über Gradle als externe Bibliothek eingebunden.
```suggestion
Sie benötigen nur das Frontend (`dungeon-starter`) für die Aufgaben, das Backend wird automatisch über Gradle als externe Bibliothek eingebunden.
```

2022-04-12 10:45 UTC, cagix commented on documentation/quickstart_de.md
> +Möchten Sie, dass Ihr Hero oder eine andere Entität nicht mehr weiter vom `EntityController` verwaltet wird, z.B. wenn sie "stirbt", überschreiben Sie dafür in der jeweiligen Klasse die Methode `remo
```suggestion
Möchten Sie, dass Ihr Hero oder eine andere Entität nicht mehr weiter vom `EntityController` verwaltet wird, z.B. wenn sie "stirbt", überschreiben Sie dafür in der jeweiligen Klasse die Methode `removeable`, die von der `Entity`-Klasse geerbt wurde. Sobald diese Methode den Wert `true` zurückgibt, wird die Instanz im nächsten Frame aus dem `EntityController` entfernt. Wie im Beispiel zu sehen, wird die Entität dann entfernt, wenn die Lebenspunkte auf 0 gefallen sind. 

Das folgende Beispiel ist für unseren Helden noch nicht direkt anwendbar (`lebenspunkte` ist noch nicht definiert), aber vielleicht wollen Sie diese Funktionalität irgendwann selbst implementieren. 
```

2022-04-12 10:47 UTC, cagix commented on documentation/quickstart_de.md
> +Beachten Sie dabei, dass `PATH/TO/FONT.ttf` wieder ein relativer Pfad, ausgehend vom `asset`-Verzeichnis ist. 
```suggestion
Beachten Sie dabei, dass `PATH/TO/FONT.ttf` wieder ein relativer Pfad, ausgehend vom `asset`-Verzeichnis ist. 
```

2022-04-12 10:48 UTC, cagix commented on documentation/quickstart_de.md
> +Freie Fonts können Sie im Internet finden. Achten Sie bitte genau darauf, ob Sie die von Ihnen verwendete Font weiterverbreiten dürfen,bevor Sie diese in Ihr Git-Repository hochladen. 
```suggestion
Freie Fonts können Sie im Internet finden. Achten Sie bitte genau darauf, ob Sie den von Ihnen verwendeten Font weiterverbreiten dürfen, bevor Sie diese in Ihr Git-Repository hochladen.
```

2022-04-12 10:50 UTC, cagix commented on documentation/quickstart_de.md
> +Aktuell wissen wir, dass Fonts vom Typen `.ttf` unterstützt werden, ob andere Fonts Typen, wie `.otf` unterstützt werden, wissen wir leider nicht.Sollten Sie Erfahrungen mit anderen Font-Typen gemach
```suggestion
Aktuell wissen wir, dass Fonts vom Typ `.ttf` unterstützt werden; ob andere Font-Typen wie `.otf` ebenfalls unterstützt werden, wissen wir leider nicht. Sollten Sie Erfahrungen mit anderen Font-Typen gemacht haben/machen, dann informieren Sie uns bitte.
```

2022-04-12 10:50 UTC, cagix requested changes
noch zwei letzte Vorschläge und dann nochmal die Ersetzung von UTF8-Sonderzeichen bei den neuen Texten

2022-04-12 10:51 UTC, cagix commented
@AMatutat Irgendwas stimmt nicht, in den neuen Texten von Dir waren wieder diese seltsamen "nicht-Blanks" drin. Ich bin zufällig drüber gestolpert, weil ich ein paar Leerzeichen hinter einigen Kommas einbauen wollte und sich dann die ganze Stelle seltsam verhielt.

2022-04-12 11:40 UTC, AMatutat commented
> @AMatutat Irgendwas stimmt nicht, in den neuen Texten von Dir waren wieder diese seltsamen "nicht-Blanks" drin. Ich bin zufällig drüber gestolpert, weil ich ein paar Leerzeichen hinter einigen Kommas einbauen wollte und sich dann die ganze Stelle seltsam verhielt.

Ich verstehe das nicht... vermutlich sollte ich mein system einfach mal neu aufsetzen.

2022-04-12 14:08 UTC, AMatutat commented
@cagix 
ich würde das jetzt mergen, ein issue für die englische version aufmachen und dann die subtrees erstellen. 
Außerdem würde ich eine Info im Ilias raushauen, da sich einige schon das Repo geforkt haben.

2022-04-12 14:10 UTC, cagix commented
> @cagix
> ich würde das jetzt mergen, ein issue für die englische version aufmachen und dann die subtrees erstellen.
> Außerdem würde ich eine Info im Ilias raushauen, da sich einige schon das Repo geforkt haben.
> Einwände?

nö, mach das so.

2022-04-12 14:11 UTC, cagix commented
> > @cagix
> > ich würde das jetzt mergen, ein issue für die englische version aufmachen und dann die subtrees erstellen.
> > Außerdem würde ich eine Info im Ilias raushauen, da sich einige schon das Repo geforkt haben.
> > Einwände?
> 
> nö, mach das so.

hmmm, ilias: nur news oder auch mail? eigentlich ist das nicht zeitkritisch, aber andererseits kriegen die premature-forker das dann evtl. zu spät mit? 

und du könntest im news sowas schreiben wie: `git remote set-url origin git@github.com:PM-Dungeon/dungeon-starter.git` für das Ändern der URL ...

2022-04-12 14:12 UTC, merged

2022-04-12 14:31 UTC, AMatutat commented
> hmmm, ilias: nur news oder auch mail? eigentlich ist das nicht zeitkritisch, aber andererseits kriegen die premature-forker das dann evtl. zu spät mit?

habs jetzt nur als news gemacht

2022-04-12 15:35 UTC, AMatutat commented
uh ne, das hab ich nicht gemacht. 

> @AMatutat hast du einen force-push auf gitlab gemacht?

kannst du das machen? Ich hab mein halbes System schon deinstalliert ^^

2022-04-12 15:39 UTC, cagix commented
> > @AMatutat hast du einen force-push auf gitlab gemacht?
> 
> uh ne, das hab ich nicht gemacht. kannst du das machen? Ich hab mein halbes System schon deinstalliert ^^

was genau machst du da? will ich das wissen? eher nein ;) ... ok, ich mach den force-push.

2022-04-12 15:42 UTC, cagix commented
@AMatutat Aber sag mal, jetzt hast Du ja auch wieder die Subtrees mit squash-merge eingebunden? D.h. beim nächsten Update haben wir das selbe Problem, nur in bunt und mit vielen Kunden?

2022-04-12 15:56 UTC, AMatutat commented
> @AMatutat Aber sag mal, jetzt hast Du ja auch wieder die Subtrees mit squash-merge eingebunden? D.h. beim nächsten Update haben wir das selbe Problem, nur in bunt und mit vielen Kunden?

Sollte gehen, hab es extra getestet. 
Beim erstellen des Subtrees sqaushed du die ganzen commits im Sub-Repo, damit kommt GIt klar.
Wenn ich das richtige verstehe, markiert sich Git jetzt den commit mit dem der Subtree angelegt wurde (wie auch immer) . 
Wenn du den Subtree jetzt in einem Branch erstellst und dann per Squash in den Master merged, dann findet Git den markierten Commit nicht wieder, da dieser im Squash-Commit eingebunden ist.

2022-04-12 16:14 UTC, cagix commented
hmmm, aber das hast du doch beim ersten mal auch so gemacht, oder hab ich grad was verpasst? ob der subtree nun in einem separaten branch oder direkt im master kommt, müsste doch eigentlich egal sein?

nagut, wenn du das getestet hast ...

2022-04-12 16:19 UTC, AMatutat commented
>  ob der subtree nun in einem separaten branch oder direkt im master kommt, müsste doch eigentlich egal sein?

Ne, musst du dir vorstellen wie diese Puppen in der wieder eine Puppe ist. 
Beim squashen schmeißt du quasi alle Commits zusammen und machst einen Ober-Commit drüber. Die kleinen Commits sind dann nicht sichtbar. 
Als ich den Branch mit den Subtrees in den Master gemerged habe, habe ich die für Git wichtigen Commits in der Puppe versteckt. 
Wir squash mergen ja immer. Bei einem normalen Merge sollte das dann problemlos gehen.

2022-04-12 16:25 UTC, cagix commented
hmmmja, ok. ich drück die daumen ;)